Обновление библиотек ОД
orangedata-official/Java-OrangeData-official pull request #6
Opened 2020-12-03 08:14 UTC by fgtmenow

2020-12-03 18:24 UTC, massivemadness requested changes

2020-12-03 18:24 UTC, massivemadness commented on .gitignore
> +.idea/jsLibraryMappings.xml
Можно добавить в исключения всю папку `.idea`

2020-12-03 18:24 UTC, massivemadness commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-bin.zip
Можно обновить до версии 6.5

2020-12-03 18:24 UTC, massivemadness commented on Example/src/main/java/ru/orangedata/example/Main.java
> +        //«акоментированы методы отправки документов, чтобы на загружались лишние документы
Опечатка или проблемы с кодировкой?

2020-12-03 18:24 UTC, massivemadness commented on orangelib/src/main/java/ru/orangedata/orangelib/CorrectionRequest.java
> +                    case 201:
Можно вынести в константы

2020-12-03 18:24 UTC, massivemadness commented on orangelib/src/main/java/ru/orangedata/orangelib/CorrectionRequest.java
> +                            postCallback.onRequestFailure(new Throwable("Wrong certificate"));
Я бы не использовал тут `Throwable`, лучше сделать какой-нибудь базовый `OrangeException` и написать ему наследников: `CertificateException`, `DocumentConflictException`, и т.д.

2020-12-03 18:24 UTC, massivemadness commented on orangelib/src/main/java/ru/orangedata/orangelib/CorrectionRequest.java
> +                            callback.onRequestFailure(new Throwable("Check had been created but has not been proceeded"));
Тут тоже самое

2020-12-03 18:24 UTC, massivemadness commented on orangelib/src/main/java/ru/orangedata/orangelib/models/correction/CorrectionDocument.java
> +                ;
форматирование поехало

2020-12-03 18:24 UTC, massivemadness commented on orangelib/src/main/java/ru/orangedata/orangelib/models/document/Payment.java
> +     * „исло от 1 до 16. ѕараметр об¤зательный.
Опечатка или проблема с кодировкой?

2020-12-03 18:24 UTC, massivemadness commented on orangelib/src/main/java/ru/orangedata/orangelib/models/document/Payment.java
> +     * ƒес¤тичное число с точностью до 2 символов после точки*. ѕараметр об¤зательный.
тут тоже

2020-12-04 07:58 UTC, fgtmenow commented on .gitignore
> +.idea/jsLibraryMappings.xml
Эт шаблонный gitignore, но ок.

2020-12-04 10:05 UTC, fgtmenow commented on orangelib/src/main/java/ru/orangedata/orangelib/models/correction/CorrectionDocument.java
> +                ;
так задумано, это конкатенация результатов функций.

2020-12-04 17:14 UTC, massivemadness approved these changes

2020-12-08 18:25 UTC, merged